// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vnlbcokzbdntnjovoyzp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZubGJjb2t6YmRudG5qb3ZveXpwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzNzQwODAsImV4cCI6MjA2Mzk1MDA4MH0.a0SA6z0Aw6IsOwNWRtyrJF0Jq3ZoGz7hIa4WWl4q1W0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);